package uk.gov.companieshouse.accounts.association.utils;

public enum EmailBatchType {

    REJECTING_INVITATION,
    AUTHORISATION_IS_BEING_REMOVED,
    ACCEPTING_INVITATION,
    CANCELLING_ANOTHER_USERS_INVITATION,
    REMOVING_ANOTHER_USERS_MIGRATED_ASSOCIATION,
    REMOVING_OWN_MIGRATED_ASSOCIATION,
    INVITING_USER,
    CONFIRMING_WITH_AUTH_CODE,
    NONE;

}


